import { css } from "../styled-system/css";

const frostedCard = {
  background: "rgba(255, 255, 255, 0.84)",
  border: "1px solid rgba(30, 29, 26, 0.08)",
  borderRadius: "panel",
  boxShadow: "card",
  backdropFilter: "blur(18px)",
};

export const styles = {
  shell: css({
    display: "grid",
    gridTemplateColumns: { base: "1fr", lg: "280px minmax(0, 1fr)" },
    minHeight: "100vh",
  }),
  sidebar: css({
    padding: { base: "6", lg: "7" },
    background: "rgba(255, 248, 236, 0.88)",
    borderBottom: { base: "1px solid rgba(30, 29, 26, 0.08)", lg: "none" },
    borderRight: { base: "none", lg: "1px solid rgba(30, 29, 26, 0.08)" },
    backdropFilter: "blur(12px)",
  }),
  brand: css({
    display: "grid",
    gap: "2",
  }),
  brandTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: { base: "3xl", md: "4xl" },
    lineHeight: 1,
    letterSpacing: "-0.03em",
  }),
  eyebrow: css({
    margin: 0,
    color: "copper",
    fontSize: "xs",
    textTransform: "uppercase",
    letterSpacing: "0.16em",
  }),
  muted: css({
    color: "muted",
  }),
  stats: css({
    display: "grid",
    gap: "3",
    marginTop: "6",
  }),
  stat: css({
    ...frostedCard,
    alignItems: "center",
    display: "flex",
    justifyContent: "space-between",
    paddingX: "4",
    paddingY: "3",
  }),
  nav: css({
    display: "grid",
    gap: "3",
    marginTop: "7",
  }),
  navItem: css({
    border: "none",
    borderRadius: "2xl",
    background: "paper",
    boxShadow: "button",
    color: "ink",
    cursor: "pointer",
    paddingX: "4",
    paddingY: "4",
    textAlign: "left",
    transitionDuration: "200ms",
    transitionProperty: "transform, box-shadow, background",
    _hover: {
      background: "paperSolid",
      boxShadow: "0 18px 34px rgba(84, 60, 28, 0.14)",
      transform: "translateY(-1px)",
    },
  }),
  content: css({
    display: "grid",
    gap: "7",
    padding: { base: "6", lg: "7" },
  }),
  header: css({
    alignItems: { base: "start", md: "end" },
    display: "flex",
    flexDirection: { base: "column", md: "row" },
    gap: "4",
    justifyContent: "space-between",
  }),
  headerBlock: css({
    display: "grid",
    gap: "1",
  }),
  runtimeTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: { base: "2xl", md: "3xl" },
    lineHeight: 1.05,
    letterSpacing: "-0.03em",
  }),
  pageGrid: css({
    display: "grid",
    gap: "4",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
  }),
  pageCard: css({
    ...frostedCard,
    display: "grid",
    gap: "3",
    padding: { base: "5", md: "6" },
  }),
  sectionTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: "xl",
    lineHeight: 1.1,
  }),
  dock: css({
    ...frostedCard,
    display: "grid",
    gap: "5",
    padding: { base: "5", md: "6" },
  }),
  dockHeader: css({
    alignItems: { base: "start", md: "end" },
    display: "flex",
    flexDirection: { base: "column", md: "row" },
    gap: "4",
    justifyContent: "space-between",
  }),
  panelGrid: css({
    display: "grid",
    gap: "4",
    gridTemplateColumns: "repeat(auto-fit, minmax(240px, 1fr))",
  }),
  panelCard: css({
    background: "rgba(255, 255, 255, 0.74)",
    border: "1px solid rgba(30, 29, 26, 0.08)",
    borderRadius: "panel",
    boxShadow: "0 12px 30px rgba(84, 60, 28, 0.08)",
    display: "grid",
    gap: "3",
    padding: "5",
  }),
  panelTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: "lg",
    lineHeight: 1.1,
  }),
  field: css({
    display: "grid",
    gap: "2",
  }),
  fieldLabel: css({
    color: "muted",
    fontSize: "sm",
  }),
  fieldControl: css({
    background: "paperSolid",
    border: "1px solid rgba(30, 29, 26, 0.12)",
    borderRadius: "xl",
    minHeight: "11",
    paddingX: "4",
    paddingY: "3",
    width: "100%",
    _focusVisible: {
      borderColor: "ember",
      outline: "2px solid rgba(183, 93, 36, 0.18)",
      outlineOffset: "2px",
    },
  }),
  primaryButton: css({
    alignItems: "center",
    alignSelf: "start",
    background: "ink",
    border: "none",
    borderRadius: "xl",
    boxShadow: "button",
    color: "paper",
    cursor: "pointer",
    display: "inline-flex",
    justifyContent: "center",
    minHeight: "11",
    paddingX: "4",
    paddingY: "3",
    transitionDuration: "200ms",
    transitionProperty: "transform, box-shadow, background",
    _hover: {
      background: "#2d2b26",
      transform: "translateY(-1px)",
    },
  }),
  statusPill: css({
    alignItems: "center",
    background: "ink",
    border: "none",
    borderRadius: "pill",
    color: "paper",
    cursor: "pointer",
    display: "inline-flex",
    fontSize: "sm",
    gap: "2",
    minHeight: "11",
    paddingX: "4",
    paddingY: "3",
  }),
  list: css({
    display: "grid",
    gap: "3",
  }),
  listRow: css({
    borderTop: "1px solid rgba(30, 29, 26, 0.08)",
    display: "grid",
    gap: "1",
    paddingY: "3",
  }),
  listTitle: css({
    fontWeight: "semibold",
  }),
  listDetail: css({
    color: "muted",
    fontSize: "sm",
  }),
};
