import { css } from "../styled-system/css";

const surface = {
  background: "rgba(255, 252, 246, 0.82)",
  border: "1px solid rgba(53, 43, 31, 0.08)",
  backdropFilter: "blur(18px)",
  boxShadow: "0 24px 60px rgba(65, 42, 18, 0.12)",
};

export const styles = {
  shell: css({
    position: "relative",
    minHeight: "100vh",
    color: "ink",
    bg: "parchment",
    overflow: "hidden",
  }),
  backdrop: css({
    position: "absolute",
    inset: 0,
    pointerEvents: "none",
    background:
      "radial-gradient(circle at 12% 18%, rgba(255, 192, 104, 0.4), transparent 24%), radial-gradient(circle at 88% 16%, rgba(89, 168, 255, 0.26), transparent 18%), radial-gradient(circle at 50% 100%, rgba(140, 97, 50, 0.18), transparent 32%)",
  }),
  layout: css({
    position: "relative",
    zIndex: 1,
    display: "grid",
    gridTemplateColumns: { base: "1fr", xl: "300px minmax(0, 1fr)" },
    minHeight: "100vh",
  }),
  sidebar: css({
    display: "grid",
    gap: "6",
    padding: { base: "5", md: "6" },
    borderRight: { base: "none", xl: "1px solid rgba(53, 43, 31, 0.1)" },
    borderBottom: { base: "1px solid rgba(53, 43, 31, 0.1)", xl: "none" },
    background: "rgba(249, 242, 231, 0.76)",
    backdropFilter: "blur(18px)",
  }),
  brandBlock: css({
    display: "grid",
    gap: "2",
  }),
  overline: css({
    margin: 0,
    color: "copper",
    fontSize: "xs",
    textTransform: "uppercase",
    letterSpacing: "0.2em",
  }),
  brandTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: { base: "4xl", md: "5xl" },
    lineHeight: 0.95,
    letterSpacing: "-0.04em",
  }),
  muted: css({
    margin: 0,
    color: "muted",
    fontSize: "sm",
  }),
  sidebarSection: css({
    display: "grid",
    gap: "3",
  }),
  statGrid: css({
    display: "grid",
    gap: "3",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  }),
  statCard: css({
    ...surface,
    borderRadius: "28px",
    padding: "4",
    display: "grid",
    gap: "1",
  }),
  statLabel: css({
    fontSize: "xs",
    textTransform: "uppercase",
    letterSpacing: "0.14em",
    color: "muted",
  }),
  statValue: css({
    fontFamily: "display",
    fontSize: "2xl",
    lineHeight: 1,
  }),
  navList: css({
    display: "grid",
    gap: "2",
  }),
  navButton: css({
    ...surface,
    borderRadius: "999px",
    paddingX: "4",
    paddingY: "3",
    textAlign: "left",
    cursor: "pointer",
    transitionDuration: "180ms",
    transitionProperty: "transform, background, box-shadow",
    _hover: {
      transform: "translateX(2px)",
      background: "rgba(255, 255, 255, 0.92)",
    },
  }),
  navButtonActive: css({
    background: "ink",
    color: "paper",
  }),
  panelStack: css({
    display: "grid",
    gap: "3",
  }),
  sidebarCard: css({
    ...surface,
    borderRadius: "28px",
    padding: "4",
    display: "grid",
    gap: "2",
  }),
  chipRow: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "2",
  }),
  chip: css({
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "999px",
    background: "rgba(255,255,255,0.72)",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    minHeight: "9",
    paddingX: "3",
    fontSize: "xs",
    color: "muted",
  }),
  chipActive: css({
    background: "rgba(183, 93, 36, 0.14)",
    color: "ink",
    borderColor: "rgba(183, 93, 36, 0.18)",
  }),
  main: css({
    display: "grid",
    gap: "5",
    padding: { base: "5", md: "6" },
  }),
  hero: css({
    ...surface,
    position: "relative",
    overflow: "hidden",
    borderRadius: "34px",
    padding: { base: "5", md: "6" },
    display: "grid",
    gap: "5",
    background:
      "linear-gradient(135deg, rgba(255,255,255,0.9), rgba(255,248,236,0.74)), radial-gradient(circle at right top, rgba(89, 168, 255, 0.22), transparent 22%)",
  }),
  heroGrid: css({
    display: "grid",
    gap: "4",
    gridTemplateColumns: { base: "1fr", lg: "1.6fr 1fr" },
  }),
  heroTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: { base: "3xl", lg: "5xl" },
    lineHeight: 0.94,
    letterSpacing: "-0.05em",
    maxWidth: "14ch",
  }),
  heroSummary: css({
    margin: 0,
    color: "muted",
    maxWidth: "62ch",
  }),
  heroMetrics: css({
    display: "grid",
    gap: "3",
    gridTemplateColumns: "repeat(2, minmax(0, 1fr))",
  }),
  heroMetricCard: css({
    borderRadius: "26px",
    background: "rgba(30, 29, 26, 0.92)",
    color: "paper",
    padding: "4",
    display: "grid",
    gap: "1",
  }),
  heroMetricValue: css({
    fontFamily: "display",
    fontSize: "2xl",
    lineHeight: 1,
  }),
  actionRow: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "3",
    alignItems: "center",
  }),
  primaryButton: css({
    border: "none",
    borderRadius: "999px",
    background: "ink",
    color: "paper",
    minHeight: "11",
    paddingX: "4",
    paddingY: "3",
    cursor: "pointer",
    transitionDuration: "180ms",
    transitionProperty: "transform, background",
    _hover: {
      transform: "translateY(-1px)",
      background: "#26231f",
    },
  }),
  secondaryButton: css({
    border: "1px solid rgba(53, 43, 31, 0.1)",
    borderRadius: "999px",
    background: "rgba(255,255,255,0.72)",
    color: "ink",
    minHeight: "11",
    paddingX: "4",
    paddingY: "3",
    cursor: "pointer",
  }),
  statusPill: css({
    display: "inline-flex",
    alignItems: "center",
    borderRadius: "999px",
    background: "rgba(255,255,255,0.72)",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    minHeight: "10",
    paddingX: "3",
    fontSize: "sm",
    color: "muted",
  }),
  stageGrid: css({
    display: "grid",
    gap: "5",
    gridTemplateColumns: { base: "1fr", xl: "minmax(0, 1.55fr) minmax(320px, 0.95fr)" },
    alignItems: "start",
  }),
  surfaceCard: css({
    ...surface,
    borderRadius: "30px",
    padding: { base: "4", md: "5" },
    display: "grid",
    gap: "4",
  }),
  sectionHeader: css({
    display: "flex",
    justifyContent: "space-between",
    gap: "3",
    alignItems: { base: "start", md: "center" },
    flexDirection: { base: "column", md: "row" },
  }),
  sectionTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: { base: "2xl", md: "3xl" },
    lineHeight: 0.98,
    letterSpacing: "-0.04em",
  }),
  sectionCopy: css({
    margin: 0,
    color: "muted",
    maxWidth: "60ch",
  }),
  workspaceGrid: css({
    display: "grid",
    gap: "4",
    gridTemplateColumns: { base: "1fr", lg: "minmax(0, 0.9fr) minmax(0, 1.2fr)" },
  }),
  composerGrid: css({
    display: "grid",
    gap: "4",
  }),
  composerCard: css({
    borderRadius: "26px",
    background: "rgba(255,255,255,0.78)",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    padding: "4",
    display: "grid",
    gap: "3",
  }),
  form: css({
    display: "grid",
    gap: "3",
  }),
  field: css({
    display: "grid",
    gap: "2",
  }),
  fieldLabel: css({
    color: "muted",
    fontSize: "sm",
  }),
  fieldControl: css({
    borderRadius: "22px",
    border: "1px solid rgba(53, 43, 31, 0.12)",
    background: "rgba(255,255,255,0.96)",
    minHeight: "11",
    width: "100%",
    paddingX: "4",
    paddingY: "3",
    _focusVisible: {
      outline: "2px solid rgba(183, 93, 36, 0.16)",
      outlineOffset: "2px",
      borderColor: "ember",
    },
  }),
  textArea: css({
    borderRadius: "24px",
    border: "1px solid rgba(53, 43, 31, 0.12)",
    background: "rgba(255,255,255,0.96)",
    width: "100%",
    paddingX: "4",
    paddingY: "3",
    minHeight: "28",
    resize: "vertical",
    _focusVisible: {
      outline: "2px solid rgba(183, 93, 36, 0.16)",
      outlineOffset: "2px",
      borderColor: "ember",
    },
  }),
  threadShell: css({
    display: "grid",
    gap: "4",
  }),
  threadList: css({
    display: "grid",
    gap: "2",
  }),
  threadButton: css({
    borderRadius: "24px",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    background: "rgba(255,255,255,0.64)",
    padding: "4",
    cursor: "pointer",
    textAlign: "left",
    display: "grid",
    gap: "1",
    transitionDuration: "180ms",
    transitionProperty: "transform, background, border-color",
    _hover: {
      transform: "translateX(2px)",
      background: "rgba(255,255,255,0.9)",
    },
  }),
  threadButtonActive: css({
    background: "rgba(183, 93, 36, 0.12)",
    borderColor: "rgba(183, 93, 36, 0.18)",
  }),
  threadTitle: css({
    fontWeight: "semibold",
  }),
  threadMeta: css({
    color: "muted",
    fontSize: "sm",
  }),
  timeline: css({
    display: "grid",
    gap: "3",
  }),
  timelineItem: css({
    borderRadius: "24px",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    background: "rgba(255,255,255,0.82)",
    padding: "4",
    display: "grid",
    gap: "2",
  }),
  timelineRole: css({
    fontSize: "xs",
    textTransform: "uppercase",
    letterSpacing: "0.14em",
    color: "copper",
  }),
  timelineBody: css({
    margin: 0,
  }),
  activityStack: css({
    display: "grid",
    gap: "4",
  }),
  list: css({
    display: "grid",
    gap: "2",
  }),
  listRow: css({
    borderTop: "1px solid rgba(53, 43, 31, 0.08)",
    paddingTop: "3",
    display: "grid",
    gap: "1",
  }),
  listTitle: css({
    fontWeight: "semibold",
  }),
  listMeta: css({
    color: "muted",
    fontSize: "sm",
  }),
  emptyState: css({
    borderRadius: "24px",
    border: "1px dashed rgba(53, 43, 31, 0.14)",
    padding: "4",
    color: "muted",
    background: "rgba(255,255,255,0.45)",
  }),
  extensionDock: css({
    ...surface,
    borderRadius: "34px",
    padding: { base: "4", md: "5" },
    display: "grid",
    gap: "4",
  }),
  extensionTabs: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "2",
  }),
  extensionTab: css({
    borderRadius: "999px",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    background: "rgba(255,255,255,0.68)",
    minHeight: "10",
    paddingX: "3",
    cursor: "pointer",
  }),
  extensionTabActive: css({
    background: "ink",
    color: "paper",
  }),
  extensionGrid: css({
    display: "grid",
    gap: "4",
    gridTemplateColumns: { base: "1fr", xl: "minmax(0, 1.1fr) minmax(300px, 0.9fr)" },
  }),
  extensionSurface: css({
    borderRadius: "28px",
    background:
      "linear-gradient(145deg, rgba(255,255,255,0.96), rgba(249,242,231,0.78))",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    padding: { base: "4", md: "5" },
    display: "grid",
    gap: "4",
    minHeight: "320px",
  }),
  extensionHero: css({
    display: "grid",
    gap: "2",
  }),
  extensionTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: { base: "2xl", md: "4xl" },
    lineHeight: 0.95,
    letterSpacing: "-0.05em",
  }),
  highlightList: css({
    display: "flex",
    flexWrap: "wrap",
    gap: "2",
  }),
  panelSlotGrid: css({
    display: "grid",
    gap: "3",
  }),
  panelSlot: css({
    borderRadius: "26px",
    border: "1px solid rgba(53, 43, 31, 0.08)",
    background: "rgba(255,255,255,0.64)",
    padding: "4",
    display: "grid",
    gap: "3",
  }),
  panelSlotTitle: css({
    margin: 0,
    fontFamily: "display",
    fontSize: "xl",
    lineHeight: 1,
  }),
  extensionPanelCard: css({
    borderTop: "1px solid rgba(53, 43, 31, 0.08)",
    paddingTop: "3",
    display: "grid",
    gap: "1",
  }),
};
